### ISSUE TITLE
增加一个橡皮擦功能

### ISSUE THREAD

**Issue by xuecq236** [Dsiner/Album#1]
想在这个基础上再增加一个橡皮擦功能有思路没。我自己尝试增加了橡皮擦画笔，但达不到预期，作者有思路可以借鉴以下嘛。。感谢

**Comment by Dsiner** [comment]
@xuecq236 类似PS的选区，Paint有Paint.setXfermode属性，选择相应的交集、并集等模式，可以实现擦除功能

**Comment by xuecq236** [comment]
> @xuecq236 类似PS的选区，Paint有Paint.setXfermode属性，选择相应的交集、并集等模式，可以实现擦除功能
自己写了个demo，是可以擦除的。但集成到DrawAttacher 中，擦除的时候变成了黑色画笔。。。

**Comment by xuecq236** [comment]
我再改了改可以了。感谢作者哈。我这个Issues可以额关了，感谢

**Comment by Dsiner** [comment]
@xuecq236 好的，很高兴能帮到你
